# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='python-deps',
    version='0.1.0',
    python_requires='==3.*,>=3.6.0',
    author='Adam Wallis',
    author_email='adam.wallis@gmail.com',
    packages=['python_deps'],
    package_dir={"": "."},
    package_data={},
    install_requires=['requests==2.*,>=2.23.0'],
    extras_require={"dev": ["pytest==5.*,>=5.2.0"]},
)
